#### Retrieval from Emails using RAG

1. Load Data from source (Kaggle)
2. Split the Text into Manageable Chunks
3. Create Embeddings and a Vector Store
4.

In [14]:
# ! pip install kaggle
# ! pip install langchain
# ! pip install openai
# ! pip install kaggle
# ! pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Collecting python-dotenv (from dotenv)
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Downloading python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv, dotenv
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [dotenv]
Successfully installed dotenv-0.9.9 python-dotenv-1.1.1

In [6]:
"""
import kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
api.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)
"""

"\nimport kaggle\nfrom kaggle.api.kaggle_api_extended import KaggleApi\napi = KaggleApi()\napi.authenticate()\napi.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)\n"

In [17]:
import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter  # For splitting large text into smaller chunks
from openai import OpenAI
import os
from dotenv import load_dotenv

In [19]:
load_dotenv()
pplx_key = os.getenv('PPLX_API_KEY')
openai_key = os.getenv('OPENAI_API_KEY')
pplx_model=os.getenv('PPLX_BASE_MODEL')
pplx_base_url = os.getenv('PPLX_BASE_URL')
print("Local config loaded")

Local config loaded

In [8]:
email_details = pd.read_csv('data/CSV/email_thread_details.csv')
email_summaries = pd.read_csv('data/CSV/email_thread_summaries.csv')

In [20]:
email_details.head()

,thread_id,subject,timestamp,from,to,body
0,1,FW: Master Termination Log,2002-01-29 11:23:42,"Gossett, Jeffrey C. JGOSSET","['Giron', 'Darron C. Dgiron', 'Love', 'Phillip...",\n\n -----Original Message-----\nFrom: =09Ther...
1,1,FW: Master Termination Log,2002-01-31 12:50:00,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Gossett', 'Jeff...",\n\n -----Original Message-----\nFrom: =09Panu...
2,1,FW: Master Termination Log,2002-02-05 15:03:35,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Anderson', 'Dia...",Note to Stephanie Panus....\n\nStephanie...ple...
3,1,FW: Master Termination Log,2002-02-05 15:06:25,"Theriot, Kim S. KTHERIO","['Hall', 'D. Todd Thall', 'Sweeney', 'Kevin Ks...",\n\n -----Original Message-----\nFrom: =09Panu...
4,1,FW: Master Termination Log,2002-05-28 07:20:35,"Kelly, Katherine L. KKELLY","['Germany', 'Chris Cgerman']",\n\n -----Original Message-----\nFrom: =09McMi...

In [21]:
email_summaries.head()

   thread_id                                            summary
0          1  The email thread discusses the Master Terminat...
1          2  A lunch meeting has been scheduled for May 5th...
2          3  Ben is updating a friend on his progress with ...
3          4  The recipient of the email thread initially ex...
4          5  The email thread discusses the long form confi...

In [22]:
email_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21684 entries, 0 to 21683
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  21684 non-null  int64
 1   subject    21684 non-null  object
 2   timestamp  21684 non-null  object
 3   from       21684 non-null  object
 4   to         21684 non-null  object
 5   body       21684 non-null  object
dtypes: int64(1), object(5)
memory usage: 1016.6+ KB

In [23]:
email_summaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  4167 non-null   int64
 1   summary    4167 non-null   object
dtypes: int64(1), object(1)
memory usage: 65.2+ KB

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=20,
)

In [39]:
print(text_splitter.split_text(email_summaries['summary'][0]))
print(text_splitter.split_text(email_details['body'][0])[1])

["The email thread discusses the Master Termination Log and the need to investigate a CNG LDC (Hope Gas) termination and a $66 million settlement offer. Stephanie Panus sends out the Daily List and Master Termination Log for various dates. Kim Theriot requests her name and Melissa Murphy's name to be removed from the distribution list and adds several names to it. The thread also includes updates on terminations and valid terminations for various companies."]
-----Original Message-----
From: =09Panus, Stephanie =20
Sent:=09Tuesday, January 29, 2002 11:39 AM
To:=09Adams, Laurel; Alonso, Tom; Aronowitz, Alan; Bailey, Susan; Balfour-F=
lanagan, Cyndie; Baughman, Edward; Belden, Tim; Bishop, Serena; Brackett, D=
ebbie R.; Bradford, William S.; Browning, Mary Nell; Bruce, James; Bruce, M=
ichelle; Bruce, Robert; Buerkle, Jim; Calger, Christopher F.; Carrington, C=
lara; Considine, Keith; Cordova, Karen A.; Crandall, Sean; Cutsforth, Diane=

In [42]:
docs, ids, metas = [], [], []

for i, row in email_details.iterrows():
    thid = str(row['thread_id'])
    text = str(row['body'])
    for k, ch in enumerate(text_splitter.split_text(text)):
        docs.append(ch)
        ids.append(f"{thid}::chunk::{k}")
        metas.append(
            {
                "thread_id": thid,
                "source" : "email_details",
                "chunk_index" : k
            }
        )

for i, row in email_summaries.iterrows():
    thid = str(row['thread_id'])
    text = str(row['summary'])
    docs.append(text)
    ids.append(f"{thid}::summary")
    metas.append(
        {
            "thread_id": thid,
            "source" : "email_summaries"
        }
    )