In [4]:
# ! pip install kaggle
# ! pip install langchain
# ! pip install openai
# ! pip install kaggle

In [6]:
"""
import kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
api.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)
"""

"\nimport kaggle\nfrom kaggle.api.kaggle_api_extended import KaggleApi\napi = KaggleApi()\napi.authenticate()\napi.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)\n"

In [7]:
import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter  # For splitting large text into smaller chunks

In [8]:
email_details = pd.read_csv('data/CSV/email_thread_details.csv')
email_summaries = pd.read_csv('data/CSV/email_thread_summaries.csv')

In [9]:
email_details

,thread_id,subject,timestamp,from,to,body
0,1,FW: Master Termination Log,2002-01-29 11:23:42,"Gossett, Jeffrey C. JGOSSET","['Giron', 'Darron C. Dgiron', 'Love', 'Phillip...",\n\n -----Original Message-----\nFrom: =09Ther...
1,1,FW: Master Termination Log,2002-01-31 12:50:00,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Gossett', 'Jeff...",\n\n -----Original Message-----\nFrom: =09Panu...
2,1,FW: Master Termination Log,2002-02-05 15:03:35,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Anderson', 'Dia...",Note to Stephanie Panus....\n\nStephanie...ple...
3,1,FW: Master Termination Log,2002-02-05 15:06:25,"Theriot, Kim S. KTHERIO","['Hall', 'D. Todd Thall', 'Sweeney', 'Kevin Ks...",\n\n -----Original Message-----\nFrom: =09Panu...
4,1,FW: Master Termination Log,2002-05-28 07:20:35,"Kelly, Katherine L. KKELLY","['Germany', 'Chris Cgerman']",\n\n -----Original Message-----\nFrom: =09McMi...
...,...,...,...,...,...,...
21679,4166,vacation,2000-10-04 11:32:00,Sara Shackleton,"['Gary Hickerson', 'Sheila Glover', 'Laurel Ad...",I will be on vacation from October 6- 13. Als...
21680,4167,web file,2001-03-18 22:57:00,Matt Smith,['Amanda Huble'],"Amanda,\n\nCan you put this file in the approp..."
21681,4167,web file,2001-03-19 04:42:00,Matt Smith,['Amanda Huble'],"Amanda,\n\nPlease move the file i sent you fro..."
21682,4167,web file,2001-03-19 09:57:00,Matt Smith,['Amanda Huble <Amanda Huble/NA/Enron@Enron'],"Amanda,\n\nCan you put this file in the approp..."
21683,4167,web file,2001-03-19 15:42:00,Matt Smith,['Amanda Huble <Amanda Huble/NA/Enron@Enron'],"Amanda,\n\nPlease move the file i sent you fro..."

In [10]:
email_summaries

      thread_id                                            summary
0             1  The email thread discusses the Master Terminat...
1             2  A lunch meeting has been scheduled for May 5th...
2             3  Ben is updating a friend on his progress with ...
3             4  The recipient of the email thread initially ex...
4             5  The email thread discusses the long form confi...
...         ...                                                ...
4162       4163  Peter Thompson has sent a memo to Kay Mann and...
4163       4164  The email thread revolves around the sharing a...
4164       4165  Susan asks Emily about her plans for the weeke...
4165       4166  Several employees will be on vacation during d...
4166       4167  Mat has sent an email to Amanda requesting her...

[4167 rows x 2 columns]

In [86]:
# create a text splitter instance
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,  # maximum size of each chunk
    chunk_overlap=50  # overlap between chunks to maintain context
)